/**
 * 169x169 all-in preflop equity matrix (class vs class, card-removal aware),
 * generated by scripts/gen-preflop-equity.ts and stored as base64 Uint16 (equity * 65535).
 */
import { PREFLOP_EQUITY_B64 } from '../data/preflopEquity';
import { NUM_CLASSES, NONCONFLICT, classComboCount } from './combos';
import type { Range } from './ranges';

let matrix: Float32Array | null = null;

function decode(b64: string): Float32Array {
  let bin: string;
  if (typeof atob === 'function') bin = atob(b64);
  else bin = Buffer.from(b64, 'base64').toString('binary');
  const out = new Float32Array(NUM_CLASSES * NUM_CLASSES);
  for (let i = 0; i < out.length; i++) {
    const v = bin.charCodeAt(2 * i) | (bin.charCodeAt(2 * i + 1) << 8);
    out[i] = v / 65535;
  }
  return out;
}

export function preflopMatrix(): Float32Array {
  if (!matrix) matrix = decode(PREFLOP_EQUITY_B64);
  return matrix;
}

/** Equity of class h against class v (all-in preflop). */
export function eqClassVsClass(h: number, v: number): number {
  return preflopMatrix()[h * NUM_CLASSES + v];
}

/** Equity of class h against a weighted range, accounting for card removal. */
export function eqVsRange(h: number, range: Range): number {
  const m = preflopMatrix();
  const base = h * NUM_CLASSES;
  let num = 0, den = 0;
  for (let v = 0; v < NUM_CLASSES; v++) {
    const w = range[v];
    if (w <= 0) continue;
    const c = w * NONCONFLICT[base + v];
    num += c * m[base + v];
    den += c;
  }
  return den > 0 ? num / den : 0.5;
}

/** Fraction of opponent combos (given we hold class h) that fall in `range`. */
export function fractionInRange(h: number, range: Range): number {
  const base = h * NUM_CLASSES;
  let num = 0, den = 0;
  for (let v = 0; v < NUM_CLASSES; v++) {
    const c = NONCONFLICT[base + v];
    num += range[v] * c;
    den += c;
  }
  return num / den;
}

let vsRandom: Float64Array | null = null;
/** Equity of each class against a random hand. */
export function equityVsRandom(): Float64Array {
  if (vsRandom) return vsRandom;
  const all = new Float64Array(NUM_CLASSES).fill(1);
  vsRandom = new Float64Array(NUM_CLASSES);
  for (let h = 0; h < NUM_CLASSES; h++) vsRandom[h] = eqVsRange(h, all);
  return vsRandom;
}

let orderCache: number[] | null = null;
/** Classes sorted by equity vs a random hand (best first). */
export function classesByRawEquity(): number[] {
  if (orderCache) return orderCache;
  const eq = equityVsRandom();
  orderCache = Array.from({ length: NUM_CLASSES }, (_, i) => i).sort((a, b) => eq[b] - eq[a]);
  return orderCache;
}

export function totalCombos(): number {
  let s = 0;
  for (let i = 0; i < NUM_CLASSES; i++) s += classComboCount(i);
  return s;
}
