/**
 * Precomputes chip-EV Nash push/fold charts (BB ante = 1bb) for 1..8 players behind and
 * stacks 1bb..25bb in 0.5bb steps: push range, BB call range, SB call range.
 * Output: src/data/pushfoldCharts.ts (bitsets, base64). Run: npm run gen:charts
 */
import { writeFileSync } from 'node:fs';
import { solvePushFold, chipOutcomes, standardSpot } from '../src/theory/pushfold';
import { NUM_CLASSES } from '../src/engine/combos';

const STEPS = 49; // 1.0 .. 25.0
const BYTES = Math.ceil(NUM_CLASSES / 8);
const buf = Buffer.alloc(8 * STEPS * 3 * BYTES);
const t0 = Date.now();
let off = 0;
const put = (r: Float64Array) => {
  for (let h = 0; h < NUM_CLASSES; h++) if (r[h] >= 0.5) buf[off + (h >> 3)] |= 1 << (h & 7);
  off += BYTES;
};
for (let k = 1; k <= 8; k++) {
  for (let i = 0; i < STEPS; i++) {
    const s = 1 + i * 0.5;
    const res = solvePushFold(chipOutcomes(standardSpot({ stackBB: s, playersBehind: k, anteBB: 1 })), 80);
    put(res.push);
    put(res.calls[k - 1]);
    put(k >= 2 ? res.calls[k - 2] : new Float64Array(NUM_CLASSES));
  }
  console.log(`k=${k} done ${(Date.now() - t0) / 1000}s`);
}
writeFileSync(new URL('../src/data/pushfoldCharts.ts', import.meta.url),
  `// Generated by scripts/gen-pushfold-charts.ts. Do not edit.\n// Layout: [k=1..8][stack 1..25 step 0.5][push, BB call, SB call] x ${BYTES}-byte bitsets.\nexport const PUSHFOLD_B64 =\n  '${buf.toString('base64')}';\n`);
