/**
 * Generates src/data/preflopEquity.ts: the 169x169 all-in preflop equity matrix.
 * For each class pair, random compatible concrete combos and random boards are sampled.
 * Run: npm run gen:equity  (takes ~1 minute)
 */
import { writeFileSync } from 'node:fs';
import { evaluate } from '../src/engine/evaluator';
import { makeRng } from '../src/engine/rng';
import { NUM_CLASSES, CLASS_COMBOS, COMBO_A, COMBO_B } from '../src/engine/combos';

const SAMPLES = Number(process.env.SAMPLES ?? 6000);
const rng = makeRng(20260930);
const eq = new Float64Array(NUM_CLASSES * NUM_CLASSES);
const buf = new Int32Array(7);
const used = new Uint8Array(52);
const t0 = Date.now();

for (let i = 0; i < NUM_CLASSES; i++) {
  for (let j = i; j < NUM_CLASSES; j++) {
    const pairs: [number, number][] = [];
    for (const a of CLASS_COMBOS[i]) for (const b of CLASS_COMBOS[j]) {
      const a1 = COMBO_A[a], a2 = COMBO_B[a], b1 = COMBO_A[b], b2 = COMBO_B[b];
      if (a1 !== b1 && a1 !== b2 && a2 !== b1 && a2 !== b2) pairs.push([a, b]);
    }
    let score = 0;
    for (let s = 0; s < SAMPLES; s++) {
      const [a, b] = pairs[rng.int(pairs.length)];
      used.fill(0);
      const h1 = COMBO_A[a], h2 = COMBO_B[a], v1 = COMBO_A[b], v2 = COMBO_B[b];
      used[h1] = used[h2] = used[v1] = used[v2] = 1;
      for (let k = 2; k < 7; k++) {
        let c: number;
        do { c = rng.int(52); } while (used[c]);
        used[c] = 1;
        buf[k] = c;
      }
      buf[0] = h1; buf[1] = h2;
      const sh = evaluate(buf, 7);
      buf[0] = v1; buf[1] = v2;
      const sv = evaluate(buf, 7);
      score += sh > sv ? 1 : sh === sv ? 0.5 : 0;
    }
    const e = score / SAMPLES;
    eq[i * NUM_CLASSES + j] = i === j ? 0.5 : e;
    eq[j * NUM_CLASSES + i] = i === j ? 0.5 : 1 - e;
  }
  if (i % 20 === 0) console.log(`row ${i}/${NUM_CLASSES} ${(Date.now() - t0) / 1000}s`);
}

const bytes = Buffer.alloc(NUM_CLASSES * NUM_CLASSES * 2);
for (let k = 0; k < eq.length; k++) bytes.writeUInt16LE(Math.round(eq[k] * 65535), 2 * k);
const out = `// Generated by scripts/gen-preflop-equity.ts (${SAMPLES} samples per matchup). Do not edit.
export const PREFLOP_EQUITY_B64 =
  '${bytes.toString('base64')}';
`;
writeFileSync(new URL('../src/data/preflopEquity.ts', import.meta.url), out);
console.log(`done in ${(Date.now() - t0) / 1000}s`);
